### ISSUE TITLE
`withTableActions` does not allow me to add a link to the drop-down menu

### ISSUE THREAD

**Issue by pavel-klimov** [gravity-ui/uikit#1061]
`Table` component has `withTableActions` HOC that does not allow me add a link as action.
In [DropdownMenu](https://github.com/gravity-ui/uikit/tree/main/src/components/DropdownMenu) it's allow.
I want this option for `Table`.

**Comment by amje** [comment]
@pavel-klimov Sounds good. Feel free to open the PR
