### ISSUE TITLE
Tooltip. Not always opens when used as `Select.Options` content

### ISSUE THREAD

**Issue by zzzorgo** [gravity-ui/uikit#1088]
Expected behaviour: tooltip is shown after the specified delay on every mouse enter
Actual behaviour: sometimes tooltip will not show (see the video)

Minimal example:
```tsx
        <Select>
            {[1, 2, 3, 4].map((num) => (
                <Select.Option
                    key={num}
                    value={num.toString()}
                    content={
                        <Tooltip content={num}>
                            <span>{num}</span>
                        </Tooltip>
                    }
                />
            ))}
        </Select>
```

https://github.com/gravity-ui/uikit/assets/17454987/0ed291eb-f4c6-476c-a804-22a1f8ad8d2d

**Comment by korvin89** [comment]
Hey @zzzorgo! Sorry for long response. This bug will be fixed [here](https://github.com/gravity-ui/uikit/pull/1239).

FYI popup won't triggered by hovering on options padding area

**Comment by korvin89** [comment]
Will be fixed in the next release
