### ISSUE TITLE
Support React Server Components for Next.js

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#1103]
Info: https://react.dev/learn/start-a-new-react-project#bleeding-edge-react-frameworks

**Comment by lu-perfect** [comment]
And add the ability to use Link from next.js by default please

**Comment by amje** [comment]
> And add the ability to use Link from next.js by default please

If you mean mixing uikit Link with next.s Link, than it can be done like that, according to [docs](https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag):

```jsx
import Link from 'next/link';
import {Link as UIKitLink} from '@gravity-ui/uikit';

<Link href={href} passHref legacyBehavior>
  <UIKitLink />
</Link>
```

**Comment by evilPaprika** [comment]
I think that the original poster talked about something like this:
https://github.com/mui/material-ui/pull/37656

**Comment by amje** [comment]
Support is coming - https://github.com/gravity-ui/uikit/pull/1582
