### ISSUE TITLE
Check if components are ready to RTL

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#1113]
After merging #1111 we should validate each component individually for rtl issues. Validation means fixing layout bugs and deprecating `left/right` properties in favor of logical ones (`start/end`). Open PRs to the `next` branch.

Validated components should be checked in the list:

- [x] ActionTooltip
- [x] ArrowToggle
- [x] Alert #1167
- [x] Breadcrumbs
- [x] Button #1119
- [x] Checkbox
- [x] Card
- [x] ClipboardButton
- [x] ClipboardIcon
- [x] CopyToClipboard
- [x] Dialog #1125
- [x] Disclosure #1140
- [x] DropdownMenu
- [x] Hotkey
- [x] Icon
- [x] Label
- [x] Link
- [x] List #1145 (need extra check)
- [x] Loader
- [x] Menu
- [x] Modal
- [x] Pagination
- [x] Persona
- [x] Popover #1125
- [x] Popup #1125
- [x] Portal
- [x] Progress #1141
- [x] Radio
- [x] RadioButton
- [x] RadioGroup
- [x] Select #1145
- [x] Sheet #1138
- [x] Skeleton #1136 
- [x] Spin
- [x] Switch #1120
- [x] Table #1152
- [x] Tabs #1148
- [x] Text #1143
- [x] Toaster #1142
- [x] Tooltip
- [x] User
- [x] UserAvatar
- [x] controls
- [x] layout

**Comment by amje** [comment]
I will check Popup, Tooltip, Modal and Dialog

**Comment by Raubzeug** [comment]
I will check ArrowToggle, Disclosure, ClipboardButton, ClipboardIcon, CopyToClipboard.

**Comment by Mishnya** [comment]
I will check Select, Sheet and Skeleton

**Comment by eyoue** [comment]
I'll check:
Progress
Breadcrumbs
Hotkey
Pagination
DropdownMenu

**Comment by korvin89** [comment]
I will check controls

**Comment by Mishnya** [comment]
I will check layout
