### ISSUE TITLE
Компоненты из Яндекс трекер и таблица 

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1135]
Вопрос по таблице и некоторых компонентах из Яндекс-трекер 

Хочется видеть из коробки такие вещи как фиксированный заголовок с виртуальным списком если мы говорим про кейс без пагинации, либо уже вложенную пагинацию при необходимости чтобы можно было обрабатывать как на клиенте так и на сервере ее. Вложенные таблицы. Компонент как в условной Chakra https://chakra-ui.com/docs/components/editable 

Так как сейчас получается так что с одной стороны мы имеем достаточно классную таблицу из коробки которая покрывает основные потребности путем использования одного компонента, но с другой стороны мы не имеем возможности ее сильно менять в виду того что это не сборная таблица как при использовании условного tanstack table

В условном яндекс трекере уже реализовано большинство классных фичей: вложенные элементы, редактируемые поля, облако фильтров, dnd для строк, sticky header и как вижу (могу ошибаться) виртуальный список
Почему бы не взять это за основую чтобы из коробки была мощная таблица которая покрывает все запросы? Просто скопировать реализацию из яндекс трекере тех или иных вещей и вынести в hoc

И еще вопрос по трекеру так как я понимаю он в большинстве своем на gravity написан

Там очень крутой gantt

Можно ли уже сейчас его как-то использовать? Или в будущем если сейчас он не вынесен в либу какую-либо?

В яндекс трекере вообще очень много компонентов которые хотелось бы в gravity увидеть: timeline в том числе и history, editable-[input], wysiwyg, autocomplete, kanban

**Comment by amje** [comment]
@lu-perfect Привет. Мы планируем развивать компонент таблицы, фиксированный заголовок и виртуализация есть в планах. А таблица, которая используется в трекере, довольно низкоуровневая и самодостаточная и скорее заслуживает быть отдельным репозиторием, чем частью uikit.

Насчет gantt и прочих компонент из трекера, планов по переносу их в опенсорс пока нет.
