### ISSUE TITLE
Компонент-контейнер

### ISSUE THREAD

**Issue by K1llMan** [gravity-ui/uikit#1163]
Есть ли в планах реализация компонента-контейнера, предоставляющего возможность настройки и показа кастомных полосок прокрутки, чтобы стиль отображения не зависел от браузера? Как пример, кастомные полоски в UI VK.

**Comment by amje** [comment]
@K1llMan Таких планов нет. Сейчас есть возможность задать [переменные](https://github.com/gravity-ui/uikit/blob/main/styles/styles.scss#L29-L61) в CSS, которые меняют внешний вид всех скроллбаров на странице
