### ISSUE TITLE
WithTableSettings. Popup is too narrow when specific conditions are met

### ISSUE THREAD

**Issue by zzzorgo** [gravity-ui/uikit#1187]
OS: MacOS
System preferences -> Appearance -> Show scroll bars -> Always
Browser: latest Firefox

If you inspect the longest item in the list you will see it to be partially hidden

![image](https://github.com/gravity-ui/uikit/assets/17454987/677b8396-536f-43eb-ae91-c06f0bdfb058)

Found a temporary workaround: set the `settingsPopupWidth` prop of the table to `'calc(100% + 16px)'`

**Comment by korvin89** [comment]
Hey @zzzorgo! Sorry for long response. It will be fixed when it will released  the new List component and the old one will be replaced by it. Issue https://github.com/gravity-ui/uikit/issues/1248
