### ISSUE TITLE
Bug: uikit/pagination component. При total = 0 неверное поведение компонента 

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1205]
При total = 0, начинается некорректное поведение, не дисейблятся кнопки, можно до бесконечности

![2023-12-15 13 24 15](https://github.com/gravity-ui/uikit/assets/104302104/0a3de907-e4e6-4dd8-b420-122397f48d79)

**Comment by jhoncool** [comment]
@lu-perfect it's okay. `total === 0` it's the same as `total === undefined`.

**Comment by lu-perfect** [comment]
> @lu-perfect it's okay. `total === 0` it's the same as `total === undefined`.

Приходится делать костыль в виде total === 0 ? 1 : total, это выглядит очень странно и неочевидно

**Comment by jhoncool** [comment]
https://github.com/gravity-ui/uikit/issues/1209 
let's discuss there

**Comment by maeshchenko** [comment]
> > @lu-perfect it's okay. `total === 0` it's the same as `total === undefined`.
> 
> Приходится делать костыль в виде total === 0 ? 1 : total, это выглядит очень странно и неочевидно

По идее, total === undefined нужен для Pagination типа total-unknown. Когда динамическая подгрузка айтемов 

Но да, тоже согласен что total===0 не должно быть тем же самым

**Comment by jhoncool** [comment]
> > > @lu-perfect it's okay. `total === 0` it's the same as `total === undefined`.
> > 
> > 
> > Приходится делать костыль в виде total === 0 ? 1 : total, это выглядит очень странно и неочевидно
> 
> По идее, total === undefined нужен для Pagination типа total-unknown. Когда динамическая подгрузка айтемов
> 
> Но да, тоже согласен что total===0 не должно быть тем же самым что и total === undefined. Особенно если этого нет в доке

Okay, we will fix it, thx

**Comment by maeshchenko** [comment]
> Okay, we will fix it, thx
I already fixed it, you can check it here https://github.com/gravity-ui/uikit/pull/1208
