### ISSUE TITLE
Bug: TextInput, Select, Safari

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1210]
<img width="393" alt="Снимок экрана 2023-12-19 в 19 51 48" src="https://github.com/gravity-ui/uikit/assets/104302104/69969c82-5b8e-463b-a3ac-e8b8c450f5a5">
<img width="368" alt="Снимок экрана 2023-12-19 в 19 51 55" src="https://github.com/gravity-ui/uikit/assets/104302104/9c4f4d79-6f6e-43c3-bb36-b0c4d9fbf675">

Safari  17.2.1. При вводе текста, TextInput начинает "прыгать", на скриншотах видна разница по отношению к верхней линии 

Баг 2: не работает фокус через tab компонента Select. допустим я в данный момент ввел что-то в TextInput, нажал Tab, и фокус переключается на TextInput который стоит после Select, а select не фокусируется. В других браузерах такого не наблюдаю

**Comment by amje** [comment]
@lu-perfect Привет. Касательно первого бага, есть issue в WebKit: https://bugs.webkit.org/show_bug.cgi?id=142968, в Safari криво работает выравнивание по baseline для флексов. Это можно пофиксить явно указав для рутового элемента TextInput vertical-align в значение != baseline, но тогда поедет выравнивание. Подумаем можно ли что-то сделать.

А насчет второго, это дефолтное поведение Safari, он фокусит по Tab только инпуты, а по Option + Tab все интерактивные элементы. Это поведение можно изменить в настройках: Safari -> Настройки -> Дополнительно -> Поставить галочку "При нажатии Tab выделать объекты последовательно"
