### ISSUE TITLE
Button. When view="raised" and disabled="true" button becomes partially transparent

### ISSUE THREAD

**Issue by zzzorgo** [gravity-ui/uikit#1212]
I expect the button with view="raised" to be always non-transparent since this view as I believe is intended to overlay buttons over some other UI-parts. See the screenshot for reference. 

![image](https://github.com/gravity-ui/uikit/assets/17454987/a5407a8a-7bfb-4656-848d-edff22914840)

**Comment by amje** [comment]
Fixed in #1226
