### ISSUE TITLE
Use logical values for direction props in CSS

### ISSUE THREAD

**Issue by ogonkov** [gravity-ui/uikit#123]
Replace direction props (left, right, top, bottom) with logical one (inline-start and etc.)

- [ ] Use `@yandex-cloud/browserslist-config`
- [ ] Use `postcss-env`

**Comment by dividead** [comment]
why is this a breaking change?

**Comment by ogonkov** [comment]
It is not anymore. When this issues was created postcss plugin required to have rtl attribute.
