### ISSUE TITLE
Add new List component to withTableSettings Table hoc

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/uikit#1248]
[Hoc](https://github.com/gravity-ui/uikit/tree/main/src/components/Table/hoc/withTableSettings)
[New List](https://github.com/gravity-ui/uikit/pull/1090)

**Comment by polikashina** [comment]
Is it an actual issue?
There is a bug with dragging items in long list, item`s content is not displayed during dragging
![image](https://github.com/gravity-ui/uikit/assets/7197224/9a662ea6-05c1-40b1-a706-e0aff49e8e01)

**Comment by GermanVor** [comment]
There is really issue connected with scroll bar, ty @polikashina.
I will fix it soon @korvin89 .

**Comment by GermanVor** [comment]
https://github.com/gravity-ui/uikit/pull/1463

**Comment by GermanVor** [comment]
@korvin89 @polikashina 

Fix is ready - https://github.com/gravity-ui/uikit/pull/1463
