### ISSUE TITLE
Playwright github actions don't work for forks

### ISSUE THREAD

**Issue by NasgulNexus** [gravity-ui/uikit#1266]
action [example](https://github.com/gravity-ui/uikit/actions/runs/7613165437/job/20732422490)

**Comment by kkirik** [comment]
> action [example](https://github.com/gravity-ui/uikit/actions/runs/7613165437/job/20732422490)

Hi, did you set a GRAVITY_UI_BOT_GITHUB_TOKEN in your forked repository?

**Comment by korvin89** [comment]
Fixed here https://github.com/gravity-ui/uikit/pull/1333
