### ISSUE TITLE
Use i18n instance from uikit

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/uikit#1280]
We should use one instance of `i18n` in all packages that completely depend on uikit
- [x] https://github.com/gravity-ui/components
- [x] https://github.com/gravity-ui/navigation
- [ ] https://github.com/gravity-ui/chartkit
- [x] https://github.com/gravity-ui/dashkit
- [x] https://github.com/gravity-ui/blog-constructor
- [x] https://github.com/gravity-ui/page-constructor

[Example](https://github.com/gravity-ui/date-components/blob/main/src/components/Calendar/i18n/index.ts)

**Comment by amje** [comment]
@korvin89 Will chartkit be updated?

**Comment by korvin89** [comment]
> @korvin89 Will chartkit be updated?

@amje  Yep, in the next major

**Comment by amje** [comment]
Closing this. Last issue recreated in chartkit repo: https://github.com/gravity-ui/chartkit/issues/494
