### ISSUE TITLE
Select: add renderFooter property

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/uikit#1297]
It will be useful to have some opportunities to render footer section in select popup. For example - to render apply button.

**Comment by GermanVor** [comment]
May be instead of `renderFooter` better have `renderPopup` ? 

something like [this](https://github.com/gravity-ui/uikit/pull/1312)

@korvin89

**Comment by korvin89** [comment]
> May be instead of `renderFooter` better have `renderPopup` ?
> 
> something like [this](https://github.com/gravity-ui/uikit/pull/1312)
> 
> @korvin89

What about all complex select logic used in popup?

**Comment by korvin89** [comment]
Added here https://github.com/gravity-ui/uikit/pull/1312
