### ISSUE TITLE
Using Gravity UI with Gatsby

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#1313]
Hi everyone! 👋 I'm new to Gatsby and I'm trying to use the Gravity UI in my project. I'm having trouble getting started, and I could use some guidance on how to set up a Gatsby project with Gravity UI.

### Here are the steps I've tried so far:
- Installed Gatsby using `gatsby new my-app --example "https://github.com/gravity-ui/gravity-ui-nextjs-example"`
- Added the Gravity UI package using `npm install gravity-ui`

However, I'm unsure about how to integrate Gravity UI components into my Gatsby project. Are there specific steps or configurations I should be aware of?

**Questions**:
1. How do I import and use Gravity UI components in my Gatsby project?
2. Are there any specific configurations or dependencies I need to be aware of?
3. How i sue Container as they say "Container
Center you content. Almost always it should be one per page. Manage max width corresponding to current screen size" 

soo if i have use layout component and i wrap my nav-bar in Container Component nd apply mx-width = 'xxl' and i want to apply background color  to nav soo its not cover the whole width insted its only cover the Container width

_Originally posted by @Saifrao1 in https://github.com/gravity-ui/uikit/discussions/1272_

**Comment by amje** [comment]
@Saifrao1

> How do I import and use Gravity UI components in my Gatsby project?`
Like any other React components, all you need is to wrap all components in `ThemeProvider` like so
```jsx
import {ThemeProvider, Button} from '@gravity-ui/uikit';

<ThemeProvider theme="light">
  <Button>Gatsby</Button>
</ThemeProvider>,
```

> Are there any specific configurations or dependencies I need to be aware of?

`react` and `react-dom` is all you need

> Center you content. Almost always it should be one per page. Manage max width corresponding to current screen size"
soo if i have use layout component and i wrap my nav-bar in Container Component nd apply mx-width = 'xxl' and i want to apply background color to nav soo its not cover the whole width insted its only cover the Container width

If I undestand correctly you need composition of following:
```jsx
<div style={{backgroundColor: '<your_color>'}}>
  <Container>
    <NavBar/>
  </Container>
</div>
<Container>
  Rest content
</Container>
```

**Comment by Saifrao1** [comment]
Thank you soo much, Please add more component  Carousel, Accordion
