### ISSUE TITLE
Dark theme misses `color-scheme: dark;` style on root element

### ISSUE THREAD

**Issue by zzzorgo** [gravity-ui/uikit#1328]
I got to know that for a proper window scrollbar color with theme "dark" you should apply the style bellow. Current dark theme doesn't apply this style so the scrollbar is white.

```css
:root {
    color-scheme: dark;
}
```
Expected color (Gitlab)
<img width="680" alt="image" src="https://github.com/gravity-ui/uikit/assets/17454987/2b268ae1-6b8c-4224-a757-b494820be2a2">

Actual color (gravity-ui)
<img width="389" alt="image" src="https://github.com/gravity-ui/uikit/assets/17454987/efd2e430-1268-451c-bcd8-b18dd1dae71f">

**Comment by korvin89** [comment]
Fixed here https://github.com/gravity-ui/uikit/pull/1468
