### ISSUE TITLE
Autoscroll to the top of page

### ISSUE THREAD

**Issue by d3m1d0v** [gravity-ui/uikit#133]
When I put `TextInput` with prop `autoFucus=true` inside `Popup`, the first time popup is opened, it scrolls to the top of page. This does not happen  with further openings.
Reproduced in sandbox: https://codesandbox.io/s/zbgwlr

**Comment by smsochneg** [comment]
Same problem with Select: https://codesandbox.io/s/mypuz5

**Comment by amje** [comment]
> Seems like there is a same problem with Select: https://codesandbox.io/s/mypuz5

It's not a problem anymore

**Comment by amje** [comment]
@d3m1d0v That's how popper works. Instead of passing autoFocus to TextInput, you should manually trigger focus on the TextInput ref
