### ISSUE TITLE
Make a layer token on `css` variables

### ISSUE THREAD

**Issue by a1eksandrk** [gravity-ui/uikit#1330]
Make a layer token on `css` variables. There are components that use `z-index`, it would be nice to standardize the use of this property to avoid problems with overlapping components (such a problem exists when using `Drawer` next to `Table` which has a sticky column). What do you think about this?

For example:
`--utility-layer: 10;`.
`--drawer-layer: 100;`
`--modal-layer: 1000;`

**Comment by korvin89** [comment]
@a1eksandrk Hey! We already have [this mechanism](https://github.com/gravity-ui/uikit/tree/main/src/components/utils/layer-manager).

@DarkGenius Hey! What do you think about using layer manager in [Drawer](https://github.com/gravity-ui/navigation/blob/main/src/components/Drawer/Drawer.tsx)?

**Comment by amje** [comment]
Issue about Drawer: https://github.com/gravity-ui/navigation/issues/208
