### ISSUE TITLE
Ability to style the “parent” element of a dropdownmenu in case submenu opened

### ISSUE THREAD

**Issue by batyrshinrn** [gravity-ui/uikit#1341]
I am trying to figure out how to style the dropdown menu item that has opening submenu

<img width="234" alt="image" src="https://github.com/gravity-ui/uikit/assets/32634525/6c5d5642-ee3b-45ce-917e-3f2285168dc0">

For now the dropdown item doesn't have any class that indicates that the submenu was opened
<img width="383" alt="image" src="https://github.com/gravity-ui/uikit/assets/32634525/e96cdfca-2439-4ceb-b228-89a51544d8bd">

As workaround I tried to use popper modifiers to apply style to popper reference, but faced that can't set handler for popper onClose event to unset the style (onClose handler is overwriting in DropDownMenuPopup, so setting onClose in popperProps has no effect).

It would be best to have some class name that would be applied to the "parent" menu item when its submenu is opened.

**Comment by amje** [comment]
UXRFC-442

**Comment by axtk** [comment]
I've come up with a PR adding a couple of classes to parent menu items as described in the [PR](https://github.com/gravity-ui/uikit/pull/1465).

Here's a demo:
https://preview.gravity-ui.com/uikit/1465/?path=/story/components-overlays-dropdownmenu--with-nested-items

For the clarity of the demo, items with the first class (with nested items) are temporarily marked with a dotted underline, and items with the second class (parent items with a currently open submenu) are marked with a blue border. Both styles will be removed before publishing this code.
