### ISSUE TITLE
Consider adding Confirm popup component

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1375]
![image](https://github.com/gravity-ui/uikit/assets/104302104/9d4441f8-1eea-493e-92a8-aaa6b4c930fa)

**Comment by amje** [comment]
@lu-perfect Looks like `Alert` inside `Popup`

**Comment by lu-perfect** [comment]
> @lu-perfect Looks like `Alert` inside `Popup`

Yes, maybe it's worth adding this component to @gravity-ui/components? In complex systems, it is often necessary to confirm certain actions and, as a rule, this component or modal window is used. Therefore, I believe that such a component in a ready-made form would simplify the development

**Comment by amje** [comment]
@lu-perfect As you mention Confirm component could be either Popup or Modal or whatever else, it depend on user's goals. We believe component composition would work better than dedicated component for confirm actions.
