### ISSUE TITLE
Alert: allow to pass null value in icon property

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/uikit#1384]
It would be useful if you want to hide the icon at all. Now there is [no options](https://github.com/gravity-ui/uikit/blob/main/src/components/Alert/Alert.tsx#L43) to do that.

**Comment by IsaevAlexandr** [comment]
Hi! It's good idea. Now only way to do this it is pass icon like this:
```tsx
<Alert icon={<Alert.Icon view="normal" />} view="success" {...props} />
```
https://github.com/gravity-ui/uikit/blob/a34db167101b17e59c0c40ce83f92059ff0b5645/src/components/Alert/AlertIcon.tsx#L48
