### ISSUE TITLE
README: it is possible to generate initial CSS-classes during SSR:

### ISSUE THREAD

**Issue by NasgulNexus** [gravity-ui/uikit#1391]
Hello, I saw the connection in Redmi

https://github.com/gravity-ui/uikit/blob/main/README.md

it is possible to generate initial CSS-classes during SSR:

```
import {getInitialRootClassName} from '@gravity-ui/uikit';

const theme = 'light';
const rootClassName = getInitialRootClassName({theme});
```

However, there is no such getInitialRootClassName function in the code. Let's remove this part of redmi or write a function that replaces it.

**Comment by amje** [comment]
@NasgulNexus Will be fixed in #1633
