### ISSUE TITLE
Anchor icon to text in Button with max size 

### ISSUE THREAD

**Issue by VitaliiDC8** [gravity-ui/uikit#1392]
Icon should be anchored to text in Button when size is max size. Right now icon be anchored to left or right in button conten layout, but it would be nice to have the feature to achor in middle close to text.
![image](https://github.com/gravity-ui/uikit/assets/127111625/9c88ad07-bbb7-4e5b-a8d7-f4f86db34398)

**Comment by amje** [comment]
Will be fixed in #1393
