### ISSUE TITLE
withTableSelection HOC does not color rows background

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/uikit#1395]
It broke down [here](https://github.com/gravity-ui/uikit/pull/1250). In the [previous PR](https://github.com/gravity-ui/uikit/pull/1255) it worked. **We need to add screenshot test for this case**.

**Comment by korvin89** [comment]
@GermanVor @Raubzeug Hey! Could you check this problem?

**Comment by GermanVor** [comment]
Did I understand correctly ?

how it should looks like:
<img width="667" alt="image" src="https://github.com/gravity-ui/uikit/assets/43282255/991c56ff-0904-4fce-9fd3-d6b9622e6d47">

and how it looks like now:
<img width="812" alt="image" src="https://github.com/gravity-ui/uikit/assets/43282255/b232f37f-5608-434a-bcaa-9332e69560a7">

@korvin89

**Comment by GermanVor** [comment]
fix is ready - https://github.com/gravity-ui/uikit/pull/1397

Did not add screenshot test - do not know how. 
If it's not difficult, please give me an example and I can do it in another PR.

**Comment by korvin89** [comment]
> fix is ready - #1397
> 
> Did not add screenshot test - do not know how. If it's not difficult, please give me an example and I can do it in another PR.
> 
> @korvin89

You can check example [here](https://github.com/gravity-ui/uikit/blob/main/src/components/Button/__tests__/Button.visual.test.tsx). It is not required but will be great to add this tests a little bit later
