### ISSUE TITLE
withTableActions HOC with onRowClick: click on action item always triggers click on row

### ISSUE THREAD

**Issue by polikashina** [gravity-ui/uikit#1398]
In this [PR](https://github.com/gravity-ui/uikit/pull/1353/files) renderRowActions property was added, and [popup](https://github.com/gravity-ui/uikit/pull/1353/files#diff-021ab63e12afe56883d225bf1ac110fa094c01cd511757aa3058e712a41716b4R154) with menu items moved to table's row subtree. Earlier [table](https://github.com/gravity-ui/uikit/pull/1353/files#diff-021ab63e12afe56883d225bf1ac110fa094c01cd511757aa3058e712a41716b4L109) was not popup's ancestor and onClick event didn't bubble to table's row. Need to add `stopPropagation` to prevent clicking on row when clicking on menu item

**Comment by polikashina** [comment]
Can you please check this [PR](https://github.com/gravity-ui/uikit/pull/1399) to fix problem?

**Comment by korvin89** [comment]
@Raubzeug Hey! Could you check this issue? I think we need a little bit more tests for Table =)
