### ISSUE TITLE
Компонент Table не отображает scroll в браузере Google Chrome

### ISSUE THREAD

**Issue by zerostar019** [gravity-ui/uikit#1415]
прикрепляю скриншоты
1. Safari
![image](https://github.com/gravity-ui/uikit/assets/104214319/3080ad93-8b97-4ddd-986e-592282df475f)
2. Google Chrome
![image](https://github.com/gravity-ui/uikit/assets/104214319/f300f52d-0b7e-4ddf-a350-eed6547f3dbb)

Песочница

https://stackblitz.com/edit/vitejs-vite-q2fw4x?file=src%2FApp.tsx

**Comment by korvin89** [comment]
@Raubzeug Hey! Could you check this one?

**Comment by Raubzeug** [comment]
@zerostar019 Hi! Could you please specify you Chrome version? I've just checked in few fresh versions and all went well without any bugs.

**Comment by zerostar019** [comment]
@Raubzeug it was the problem of my OS. Do I have to delete that issue?
