### ISSUE TITLE
[DropDownMenu] Can't open the 3rd level submenu in case using items groups

### ISSUE THREAD

**Issue by batyrshinrn** [gravity-ui/uikit#1442]
Trying to add the 3rd level submenu to the DropDownMenu component. Everything works fine in case items props has only one group (in all levels), but when you try to add multiple groups (also in any level), the 3rd level submenu is displayed and immediately disappears as soon as you hover the cursor over the parent level. The parent level is also being closed

Issue example: https://stackblitz.com/edit/vitejs-vite-logww1

**Comment by korvin89** [comment]
@axtk Would you triage this problem? Looks not good

**Comment by axtk** [comment]
Yep, I'll look into that

A quick and obvious workaround is to use a menu with nested items without groups before we roll out a fix
