### ISSUE TITLE
Bug(Button): Incorrect button behavior in next js 14 ssr

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1445]
Incorrect button behavior in next js 14 ssr

![telegram-cloud-photo-size-2-5469668932408432187-m](https://github.com/gravity-ui/uikit/assets/104302104/8d4d6fba-982b-452e-9b8b-efa8c9ece4d9)
![telegram-cloud-photo-size-2-5469668932408432188-x](https://github.com/gravity-ui/uikit/assets/104302104/10d1706f-c210-4f00-a6e8-2b7c8014034a)

[use case](https://codesandbox.io/p/devbox/compassionate-fast-l4k2tz?workspaceId=23d880bc-65e0-43a7-9728-0288d5def32a&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2v236000073b6hketkhorb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2v236000023b6hw2yk1fun%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2v236000043b6h6vmwiel0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2v236000063b6hqzvgyn4t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2v236000023b6hw2yk1fun%2522%253A%257B%2522id%2522%253A%2522clu2v236000023b6hw2yk1fun%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu2v236000063b6hqzvgyn4t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2v236000053b6habkstgyx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2v236000063b6hqzvgyn4t%2522%252C%2522activeTabId%2522%253A%2522clu2v236000053b6habkstgyx%2522%257D%252C%2522clu2v236000043b6h6vmwiel0%2522%253A%257B%2522id%2522%253A%2522clu2v236000043b6h6vmwiel0%2522%252C%2522activeTabId%2522%253A%2522clu2w5lme01pj3b6hqcw2me4k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2v236000033b6hffhtsmao%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu2w5lme01pj3b6hqcw2me4k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu2w5lrk00jdefi9014gbjff%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by amje** [comment]
@lu-perfect Should be fixed now. Is it still reproducable in the latest version?
