### ISSUE TITLE
Bug(Sheet): animation lags on mobile devices

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1530]
The animation lags on mobile devices if you drag it instead of swiping it

**Comment by korvin89** [comment]
cc @mournfulCoroner

**Comment by mournfulCoroner** [comment]
@lu-perfect, can you please try to make a screencast? I tried Android and iPhone, and couldn't notice the problem. Maybe I'm just used to this lag.

**Comment by lu-perfect** [comment]
https://github.com/gravity-ui/uikit/assets/104302104/a8308ed5-cd7f-49bb-b9cd-dc589593ffb1

**Comment by lu-perfect** [comment]
Когда начинаем вести компонент вниз он сначала ничего не делает а потом резко срывается на середину 
Браузер сафари, iphone
