### ISSUE TITLE
Feat(Tooltip): improve behavior on mobile devices

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1531]
![image](https://github.com/gravity-ui/uikit/assets/104302104/6fc9fea4-3422-49d3-ae4c-3652aa9b6b48)

Also, the tooltip has a different behavior: it somehow opens randomly, either on the second click or on the third

**Comment by lu-perfect** [comment]
> What device are you using?

iPhone

**Comment by amje** [comment]
@lu-perfect  Cannot reproduce. Could you record a screencast from your phone on storybook example?
