### ISSUE TITLE
AdaptiveDialog 

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1533]
Please add a responsive dialog component and adapt components from your other libraries that use it

**Comment by amje** [comment]
@lu-perfect What is responsive dialog? Flexible width?

**Comment by lu-perfect** [comment]
@amje We discussed this with Patrick in the chat that your dialog component is considered a desktop solution. Therefore, it was proposed to implement a separate responsive dialog, which is used in the mobile version of sheet

**Comment by lu-perfect** [comment]
![IMG_0565](https://github.com/gravity-ui/uikit/assets/104302104/5245a6d4-82c9-4dc4-bba8-402c734e2b91)
