### ISSUE TITLE
Label animation transition lag

### ISSUE THREAD

**Issue by korvin89** [gravity-ui/uikit#1534]
Sandbox https://stackblitz.com/edit/vitejs-vite-p75yxe?file=src%2FApp.tsx,src%2Fmain.tsx

https://github.com/gravity-ui/uikit/assets/26501073/ed009c97-fca9-4d34-8dd0-9d016cfedca4

**Comment by itwillwork** [comment]
https://github.com/gravity-ui/uikit/pull/1590

**Comment by itwillwork** [comment]
https://github.com/gravity-ui/uikit/pull/1590#issuecomment-2133831297
