### ISSUE TITLE
Unable to click Switch in Playwright

### ISSUE THREAD

**Issue by ogonkov** [gravity-ui/uikit#1556]
I've tried to click on `Switch` in Playwright via selector

```ts
getByRole('switcher', {name: 'Some switcher name'})
```

But Playwright is unable to do it, because of a error

```
<span class="g-switch__slider"></span> intercepts pointer events
```

Looks like this element is laying over original input, and this cause error.

**Comment by amje** [comment]
@ogonkov Yes, indeed we have complex layout for this control. For such case you can [force](https://playwright.dev/docs/input#forcing-the-click) playwright to click
