### ISSUE TITLE
Documentation does not match components

### ISSUE THREAD

**Issue by SimbiozizV** [gravity-ui/uikit#1574]
I encountered that the properties of the Link component do not correspond to the documentation on the site https://gravity-ui.com/components/uikit/link

Previously, the href property was optional and this was indicated in the documentation, but with pr https://github.com/gravity-ui/uikit/pull/1270 this has changed.

There is no documentation for version 6.15.0 and it is a bit misleading.

**Comment by korvin89** [comment]
@SimbiozizV Hey! It is indicated [here](https://gravity-ui.com/components/uikit/link#href), but there is one inaccuracy in properties table, we will fix it
