### ISSUE TITLE
Bug(Select): ID does not get into the control component

### ISSUE THREAD

**Issue by a1eksandrk** [gravity-ui/uikit#1600]
Usage:
```jsx
<FormRow fieldId="select" label="Label" direction="column">
  <Select id="select" placeholder="Template" />
</FormRow>
```

Result:
<img width="523" alt="image" src="https://github.com/gravity-ui/uikit/assets/60098929/5288092b-909f-45b0-8e76-454224db4b40">

Sandbox: https://stackblitz.com/edit/vitejs-vite-fazud2?file=src%2FApp.jsx,src%2Fmain.jsx&terminal=dev

**Comment by GermanVor** [comment]
https://github.com/gravity-ui/uikit/pull/1604
