### ISSUE TITLE
Table improvements: add icons for actions in withTableActions HOC

### ISSUE THREAD

**Issue by shbov** [gravity-ui/uikit#1622]
Is it possible to add `icon?: Pick<IconProps, 'data' | 'size'>` prop in the `TableAction` type and display them only if all actions are provided with icons? uikit already has an `IconProps` interface

It would be nice to have action with icon in the `Table` component for better UX
<img width="836" alt="image" src="https://github.com/gravity-ui/uikit/assets/32542672/64b8184b-7958-40e3-9911-7b88fc1c66e7">

**Comment by amje** [comment]
@shbov It's already implemented:

```jsx
import {Printer} from '@gravity-ui/icons';

<Table getRowActions={() => [{text: 'Print', icon: <Icon data={Printer} size={12} />}]}/>
```

I've imporved Table example here: https://github.com/gravity-ui/landing/pull/211
