### ISSUE TITLE
Coercion to use ThemeProvider

### ISSUE THREAD

**Issue by Fettser** [gravity-ui/uikit#1632]
The documentation suggests using two different approaches to provide theme: CSS classes and ThemeProvider. My project based on SSR, therefore I prefer to use CSS classes (ThemeProvider uses useLayoutEffect inside, that works incorrectly with SSR). In the 5-th version CSS classes works, in the 6-th you must use ThemeProvider (some components depend on ThemeContext). When the library allows two methods, it seems like a bug. For example:
![photo_2024-06-07_15-09-49](https://github.com/gravity-ui/uikit/assets/75333437/d9275e9d-f6c7-4829-83eb-095f5868d0aa)

**Comment by amje** [comment]
@Fettser It's not a bug, since v6 wrapping your App inside the `ThemeProvider` is mandatory. I've fixed the docs in #1633

**Comment by Fettser** [comment]
@amje, I think the ability to use ThemeProvider with SSR needs to be added (for example, use safe useLayoutEffect)
