### ISSUE TITLE
UserLabel не реализует поддержку свойства size

### ISSUE THREAD

**Issue by issamansur** [gravity-ui/uikit#1649]
Доброго времени суток. В [документации](https://gravity-ui.com/design/guides/user) на сайте у компонента `UserLabel` имеется свойство size, которое по идее должно устанавливать высоту для самого компонента `UserLabel`, так и для `Avatar`, используемого внутри.
Но такое свойство отсутствует, как и логика изменения компонента при просто установке размера компоненту <Avatar>:
```
<UserLabel
    view="outlined"
    type="person"
    avatar={<Avatar text={username} size="l" />}
    onClick={onClickHandler}
>
    {username}
</UserLabel>
```
Остаётся лишь указывать размер и самому `UserLabel`, что не особо привлекает:
```
<UserLabel
    style={{height: 42 }}
    view="outlined"
    type="person"
    avatar={<Avatar text={username} size="l" />}
    onClick={onClickHandler}
>
    {username}
</UserLabel>
```

**Comment by amje** [comment]
@issamansur Привет! Документация описывает компонент `User`, не `UserLabel`. Для `User` можно установить размер, см. [сторибук](https://preview.gravity-ui.com/uikit/?path=/docs/components-data-display-user--docs).

**Comment by issamansur** [comment]
> @issamansur Привет! Документация описывает компонент `User`, не `UserLabel`. Для `User` можно установить размер, см. [сторибук](https://preview.gravity-ui.com/uikit/?path=/docs/components-data-display-user--docs).

прошу прощения, ошибся ссылкой:
https://gravity-ui.com/design/guides/user-label

**Comment by amje** [comment]
@issamansur Да, размера действительно не хватает. Завел issue на доработку #1655

**Comment by issamansur** [comment]
Благодарю)
