### ISSUE TITLE
Improve(Modal): добавить базовые элементы

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1654]
Сейчас есть компонент Dialog, предлагаю добавить базовые компоненты для Modal, чтобы пользователи могли композитно собирать то, что им нужно, при этом не пересобирая велосипед, но и не разбирая компонент Dialog
Предлагаю следующие компоненты:
- ModalHeader 
  - ModalHeader.Title
  - ModalHeader.Description 
  - ModalHeader.MaximizeButton
  - ModalHeader.CloseButton 
- ModalBody
- ModalFooter
  - ModalFooter.CloseButton
  - ModalFooter.ApplyButton

ModalHeader:
- добавить position: sticky/not-sticky, чтобы header прикреплялся к верху или при скроле уезжал 

ModalHeader.MaximizeButton:
-  во многих модалках хочется дать возможность развернуть на полный экран  
![image](https://github.com/gravity-ui/uikit/assets/104302104/92981a6d-08c8-4be6-9aa6-2be296442466)

ModalHeader.CloseButton:
- предусмотреть позиционирование внутри (то что сейчас в Dialog) и снаружи, так как в некоторых модалках много действий или текста внутри header
![image](https://github.com/gravity-ui/uikit/assets/104302104/856de8e1-c283-41b9-bbb4-b34e55baee16)
- также предусмотреть поведение на мобилках, если был outside, хотелось бы скрыть или переместить внутрь 

Композитный подход удобнее, чем подход рендеров или полной реализации своего велосипеда.

**Comment by amje** [comment]
`Modal` - совсем базовый компонент. Там нет и не должно быть ничего сложного, это просто контейнер с бекдропом, мы не хотим его усложнять. На его основе сделан `Dialog`, в котором такие элементы уже есть, это готовое решение от нас. Если оно не подходит, то всегда можно взять `Modal` и наполнить его своими компонентами.

> также предусмотреть поведение на мобилках, если был outside, хотелось бы скрыть или переместить внутрь

На мобильных устройствах мы рекомендуем использовать `Sheet` вместо `Modal`
