### ISSUE TITLE
Slider + Sheet, уезжает шторка на мобильных устройствах

### ISSUE THREAD

**Issue by lu-perfect** [gravity-ui/uikit#1659]
https://stackblitz.com/edit/vitejs-vite-adc1ru?file=src%2FApp.tsx

При комбинации шторки и слайдера, при слайде, шторка начинает убегать

![telegram-cloud-photo-size-2-5443003378843115770-y](https://github.com/gravity-ui/uikit/assets/104302104/b200e254-a754-4eed-a61e-f39fde58ec6b)

**Comment by korvin89** [comment]
@Arucard89 Hey! Could you check this problem?

**Comment by Arucard89** [comment]
@lu-perfect, привет! 
У компонента Sheet есть свойство allowHideOnContentScroll - его нужно выставить в false.  
```ts
<Sheet
        visible={visible}
        onClose={() => setVisible(false)}
        title="Фильтры"

        allowHideOnContentScroll={false} 
> 
... 
</Sheet>
```
При такой настройке компонента работа слайдера не будет влиять на поведение шторки.

**Comment by korvin89** [comment]
@Arucard89 но там же не про скролл речь? Мне кажется тут проблема в том, что stopPropаgation в Slider ломает шторку

**Comment by Arucard89** [comment]
> @Arucard89 но там же не про скролл речь? Мне кажется тут проблема в том, что stopPropаgation в Slider ломает шторку

Проблема появляется только при включении перемещения шторки через протаскивание по области ее контента. 
Да, @korvin89, ты абсолютно прав: такое вызвано прерыванием распространения события в слайдере: https://github.com/react-component/slider/blob/master/src/hooks/useDrag.ts#L99

выключение allowHideOnContentScroll предложенное мной выше - это временное решение проблемы, чтобы сайт мог работать уже сейчас, не дожидаясь выхода новой версии библиотеки.

Сейчас я сделал фикс, который позволяет компоненту Sheet правильно обрабатывать подобные случаи.

**Comment by Arucard89** [comment]
@lu-perfect, привет. 
фикс уже в релизе 6.19(https://github.com/gravity-ui/uikit/blob/main/CHANGELOG.md#bug-fixes). можно обновиться и отказаться от проставления allowHideOnContentScroll, если он не нужен.
