### ISSUE TITLE
Modal without title

### ISSUE THREAD

**Issue by persovt2** [gravity-ui/uikit#1680]
Есть в модалке не указывать title в Modal.Header
К примеру нужно только закрытие модалки, то контент наезжает на крестик
У себя сделали костыль с невидимым символом в title

**Comment by amje** [comment]
Речь видимо про Dialog и его Dialog.Header. Это может не очевидно, но если Dialog.Header не рендерить, то компонент не может знать как правильно ему резервировать место под крестик, это остается на откуп пользователя.
