### ISSUE TITLE
Add `2xs` Avatar size

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#1699]
UXRFC-454

- Need to add a new `size` value, `2xs` in the `Avatar` component for 20x20 dimensions
- Ensure that new size is available for all components using the `Avatar` (UserAvatar, UserLabel)

**Comment by rLukoyanov** [comment]
`UXRFC-454` - номер задачи? Если да, то где можно найти более подробное описание?

**Comment by amje** [comment]
> `UXRFC-454` - номер задачи? Если да, то где можно найти более подробное описание?

Да, это внутренний номер задачи, дополнил описание
