### ISSUE TITLE
Component: RelativeDatePicker, props -> format doesn't support latin literal "T", only cyrillic literal "T"

### ISSUE THREAD

**Issue by ZeraiGR** [gravity-ui/uikit#1702]
For example:
```
<DatePicker
    format="YYYY-MM-DDTHH:mm:ss" // T is latin
/>
```
console print the following error: `"The token "DDTHH" is not supported by the Date field. Please try using another token."`
and ui of DatePicker will be broken and show something like this: `2024-07-DDTHH:00:00`
```
<DatePicker
    format="YYYY-MM-DDТHH:mm:ss" // T is cyrillic
/>
```
ok

**Comment by korvin89** [comment]
сс @ValeraS

**Comment by ValeraS** [comment]
Any text inside brackets will be used as is. In your case use this `format="YYYY-MM-DD[T]HH:mm:ss"`
