### ISSUE TITLE
Switching language on Firefox Ubuntu close select

### ISSUE THREAD

**Issue by dsleepo** [gravity-ui/uikit#1737]
1. Open filterable select
2. Press `super` + `space`

Actual result: option's popup closed
Expected: option's popup remains open

[DELL-LATITUDE-E7440-(1920x1080,-Intel-Core-i5-1-6-ГГц,-RAM-8-ГБ,-SSD-128-ГБ,-Win7-Pro-64)_Ubuntu-20-04_07-08-2024_14-54-24.webm](https://github.com/user-attachments/assets/3e3e951a-d91b-4a41-ac85-6dcd1d196c4e)

**Comment by lxndr** [comment]
I can reproduce it having GNOME 46, Wayland, Firefox 129. If I have time, I could take a closer look what's going on. Not a lot of Linux users around here.

**Comment by lxndr** [comment]
I can reproduce it having GNOME 46, Wayland, Firefox 129. If I have time, I could take a closer look what's going on. Not a lot of Linux users around here.

**Comment by lunaticenslaved** [comment]
If you do not mind I take part.

I reproduced the issue on Manjaro + Firefox 130 with `super` + `space`. Moreover I emulated it with Macbook:
1. In Firefox open any select.
2. Click `control` + `space` to open search bar.

Apparently blur event is fired when FIrefox's window loses focus. It was discussed here: https://stackoverflow.com/questions/19700476/avoid-element-blur-handler-when-window-blur-invoked-browser-loses-focus

If you please I want to suggest a solution: #1836
