### ISSUE TITLE
TextInput bug: note props

### ISSUE THREAD

**Issue by bratva** [gravity-ui/uikit#1886]
In the storybook [I](https://gravity-ui.com/components/uikit/text-input), when you specify a `note`, it overlaps the text field. This looks like an error.

<img width="315" alt="Screenshot 2024-10-07 at 22 05 57" src="https://github.com/user-attachments/assets/f454e166-d6d7-4dc9-80a2-4cb1fbdb0daf">

Yandex.Browser 24.7.6.968 (64-bit)
MacOs 14.7

**Comment by arteria32** [comment]
Hi! 👋
Thanks for bringing the issue, fixed in version [6.38.0](https://github.com/gravity-ui/uikit/releases/tag/v6.38.0)
