### ISSUE TITLE
Rename variable --g-button-icon-size

### ISSUE THREAD

**Issue by Raubzeug** [gravity-ui/uikit#1899]
For now we have `--g-button-icon-size` css-variable, which has no influence on button icon size. We calculate icon's margin with help of this property. Let's rename it to clear it's function.

**Comment by amje** [comment]
@Raubzeug What's your suggestion? `--g-button-icon-space`?

**Comment by Raubzeug** [comment]
> @Raubzeug What's your suggestion? `--g-button-icon-space`?

looks nice!

**Comment by blasdfaa** [comment]
can i take this?
