### ISSUE TITLE
Getting "Error: Can't resolve './text.css' in './node_modules/@gravity-ui/uikit/build/esm/components/Text/text'"

### ISSUE THREAD

**Issue by lxndr** [gravity-ui/uikit#1942]
Hi! I'm getting a build error while using 6.35.0.

I checked npm package and there's no text.css while text.js contains `import './text.css';`

<img width="305" alt="Screenshot 2024-11-13 at 16 23 21" src="https://github.com/user-attachments/assets/baab7a04-745f-4045-ba9a-6d385553b20b">

**Comment by lxndr** [comment]
So, it's not just Text component. css in /components/*/*/*.css don't seem to be there at all.

**Comment by amje** [comment]
Fixed in #1943
