### ISSUE TITLE
Card onClick for container

### ISSUE THREAD

**Issue by ierehon1905** [gravity-ui/uikit#204]
https://github.com/yandex-cloud/uikit/blob/bd52a232dbcf913d5101a45ce5bed01873a46a69/src/components/Card/Card.tsx#L18

Hi, I have encountered some problems implementing `onCLick` of `Card`. It seems it is explicitly disabled. But our design says todo a `container` type `Card` with click handler.

Is there any way we could enable click handler for container type?

**Comment by amje** [comment]
Waiting design for hover/active states

**Comment by amje** [comment]
For actions we have type `action`. Not planning add click handler on other types. Feel free to reopen for further discussion
