### ISSUE TITLE
UIKit v4

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#221]
- [ ] React 18
- [ ] Single CSS bundle

**Comment by ogonkov** [comment]
@amje  We can also remove Toaster singleton (and it legacy methods), i just merged context for working with Toaster via hooks/hoc

**Comment by resure** [comment]
Pending breaking changes to consider:

- #241 
- #238 
- #222 
- #123

**Comment by ogonkov** [comment]
I have approval for #241 and #222 from @korvin89 and #238 from @amje
