### ISSUE TITLE
Text: Typo on colorText

### ISSUE THREAD

**Issue by ierehon1905** [gravity-ui/uikit#259]
Hi,

We found that `warningheavy` in the sources is written without `-`. Maybe it should be written like `warning-heavy`, similarly to `warning-medium`

https://github.com/yandex-cloud/uikit/blob/857e434b4cd619992a900156ebcfd39d5668a187/src/components/Text/c/colorText.ts#L15

Also we have a trouble finding how to make our text bold without writing our own classes/styles. Is there a prop we could use to achieve that?

**Comment by IsaevAlexandr** [comment]
Hi!
Feel free to make pr with correction of this types of issues. Here https://github.com/yandex-cloud/uikit/pull/264 i fix this

What about of font weight prop on this component, i think it's useful, but there can be some potential problems. https://github.com/yandex-cloud/uikit/pull/265 where is pr with proposal with this ability and explanation

**Comment by ierehon1905** [comment]
> Hi! Feel free to make pr with correction of this types of issues. Here #264 i fix this
> 
> What about of font weight prop on this component, i think it's useful, but there can be some potential problems. #265 where is pr with proposal with this ability and explanation

Wow, thank you so much for the feature. Hope the PR is merged soon :)

**Comment by IsaevAlexandr** [comment]
anyway, i have i ~bad~ advise for you:)

It is a good practice to override all components on you project level. Now you can add any functionality to any entity, but now you have to maintain it.

in this issue example you can do something like this:
```js
// we are in `src/components/Text`
import {Text as TextBase, TextProps as TextBaseProps} from '@uikit';

interface TextProps extends TextBaseProps {
  weight: 'type1' | 'type2';
}

export const Text = ({weight, className, ...props}) => <TextBase {...props} className={b({weight}, className)} />
```
