### ISSUE TITLE
Translate to English

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#31]
- [x] Breadcrumbs #232
- [x] Button
- [x] Card #32 
- [x] Checkbox #233 
- [x] ClipboardButton #233
- [ ] ClipboardIcon **no README**
- [x] CopyToClipboard #233
- [x] DropdownMenu #244 
- [ ] Icon **no README**
- [x] Label #233
- [ ] Link **no README**
- [x] List
- [ ] Menu **no README**
- [ ] Modal **no README**
- [x] Popover #233 
- [ ] Portal **no README**
- [x] Progress #42 
- [x] Radio #233
- [x] RadioButton #233
- [x] RadioGroup
- [x] Skeleton #233
- [x] Spin #233
- [x] Switch #233
- [x] Table
- [x] Tabs
- [x] TextInput - storybook still untranslated
- [x] User #233
- [x] UserAvatar #244

**Comment by teleginzhenya** [comment]
- [ ] Breadcrumbs
- [ ] Button
- [x] Card #32 
- [ ] Checkbox
- [ ] ClipboardButton
- [ ] ClipboardIcon **no README**
- [ ] CopyToClipboard
- [ ] DropdownMenu
- [ ] Icon **no README**
- [ ] Label
- [ ] Link **no README**
- [ ] List
- [ ] Menu **no README**
- [ ] Modal **no README**
- [ ] Popup **no README**
- [ ] Portal **no README**
- [ ] Radio
- [ ] RadioButton
- [ ] RadioGroup
- [ ] Skeleton
- [ ] Spin
- [ ] Switch
- [ ] Table
- [ ] Tabs
- [ ] TextInput
- [ ] User
- [ ] UserAvatar

**Comment by ogonkov** [comment]
@teleginzhenya `Popup` is now `Popover`

**Comment by ogonkov** [comment]
@amje can we move checklist to issue description to see translation progress?
