### ISSUE TITLE
i18n package version

### ISSUE THREAD

**Issue by ierehon1905** [gravity-ui/uikit#312]
Hi, there was an update in i18n that removed usage of static methods. I think we could upgrade here to the newest version

https://github.com/yandex-cloud/uikit/blob/c338449c56bb5a3560e5d378bedfa3107e33d730/package.json#L67

**Comment by ogonkov** [comment]
From my understanding, this is postponed, because it is breaking change.

**Comment by ValeraS** [comment]
updated
