### ISSUE TITLE
Fix propagation from popover to link

### ISSUE THREAD

**Issue by saxumcordis** [gravity-ui/uikit#388]
If link wraps popover or popovers child is link, the click on popover content will activate the link

For example,
```
<Link> ... <Popover> . . </Link>
<Popover><Link ... /></Popover>
```

**Comment by amje** [comment]
@saxumcordis Cannot reproduce it. I've tried to put a Button inside Popover's content. Popover itself is inside a Link. Like this:

```jsx
<Link href=".">
    <Popover content={<Button>Click me</Button>}>Link</Popover>
</Link>
```
