### ISSUE TITLE
Migrate from Popper to Floating UI

### ISSUE THREAD

**Issue by ValeraS** [gravity-ui/uikit#418]
https://github.com/floating-ui/floating-ui

https://floating-ui.com/docs/migration

**Comment by Arucard89** [comment]
I'm ready to do it

**Comment by amje** [comment]
We delay it until FloatingUI is v1.0.0

**Comment by amje** [comment]
Seems we don't need the `@floating-ui/react` which is pre v1 version and only need `@floating/react-dom`. We can start migration now
