### ISSUE TITLE
Refactor Sheet and PromoSheet components

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#435]
These components were migrated "as is" from internal codebase. We should change theirs code and api in uikit way

**Comment by korvin89** [comment]
`Sheet` component:
1. Rewrite  as functional component
2. Use [this](https://www.npmjs.com/package/tinygesture) lib for swipe actions

`PromoSheet` component: move to [components](https://github.com/gravity-ui/components)

**Comment by korvin89** [comment]
Fixed here https://github.com/gravity-ui/uikit/pull/1268
