### ISSUE TITLE
Improve typings in Select

### ISSUE THREAD

**Issue by Marginy605** [gravity-ui/uikit#552]
- Make separate type for renderControl and onOpenChange args
- Extend type for ref in renderControl args (I get error in class component with ref: `Type 'Ref<HTMLElement>' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.`)

**Comment by imechoim** [comment]
- ~~Make separate type for renderControl and onOpenChange args~~
- Extend type for ref in renderControl args (I get error in class component with ref: `Type 'Ref<HTMLElement>' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.`)

**Comment by imechoim** [comment]
@Marginy605 
Is this modifications still necessary?

**Comment by Marginy605** [comment]
> @Marginy605
> Is this modifications still necessary?

Still need this "Make separate type for onOpenChange args". Other items are not actual

**Comment by imechoim** [comment]
@Marginy605 
You can extract this type by using the following:

```typescript
type OnOpenChengeParams = Parameters<NonNullable<SelectProps['onOpenChange']>>;
```

This is not an easy but legal way.
