### ISSUE TITLE
RadioButton is not accessible from keyboard

### ISSUE THREAD

**Issue by KalachevDev** [gravity-ui/uikit#560]
Currently, it's not possible to select RadioButton component options from keyboard. I think it needs to be fixed.

[Component Storybook](https://preview.gravity-ui.com/uikit/?path=/story/components-radiobutton--default)

**Comment by ogonkov** [comment]
Worked for me. Options changed with arrows.

**Comment by KalachevDev** [comment]
@ogonkov yeah, arrows work for me as well. However, I did expect it to work with tabs :/

**Comment by ogonkov** [comment]
Nope, arrow is a way. That how radio group should interact with keyboard input. https://www.w3.org/WAI/ARIA/apg/patterns/radio/

**Comment by KalachevDev** [comment]
@ogonkov okay, sounds good. Closing the issue then, thanks!
