### ISSUE TITLE
Link compatibility with routers

### ISSUE THREAD

**Issue by LakeVostok** [gravity-ui/uikit#604]
Routing libraries provide components for spa navigation([example](https://reactrouter.com/en/main/components/link#link)), but they don't have the same styles as the Link from uikit. 
To get a stylized component, a hard-coded class name "yc-link yc-link_view_normal" is passed to it. 
I suggest adding an optional render prop to Link (after merge https://github.com/gravity-ui/uikit/pull/600) to connect such components with the style guide.

**Comment by amje** [comment]
@LakeVostok Are you looking for smth like this https://reactrouter.com/en/main/hooks/use-link-click-handler ?

**Comment by amje** [comment]
Reopen this if it still a problem
