### ISSUE TITLE
Incorrect height of TextInput multiline after display:none of container

### ISSUE THREAD

**Issue by nikita-jpg** [gravity-ui/uikit#623]
If TextInput is in a container with ```display:none```, and then becomes visible (for example ```display:flex```), then the height of TextInput becomes 0, even if there is text in TextInput. This only reproduced with the ```multiline``` prop. Without it, the content is displayed.

I think the problem is in this [place](https://github.com/gravity-ui/uikit/blob/e67ce4dfb01a36ec7339ef99cff55d59bf04cd1c/src/components/TextInput/TextAreaControl/TextAreaControl.tsx#L61). If ```display:none```, then ```control.scrollHeight = 0```

https://codesandbox.io/s/pensive-feather-vr0uwg?file=/src/App.js
<img width="1440" alt="Снимок экрана 2023-04-13 в 16 19 16" src="https://user-images.githubusercontent.com/56046344/231788473-cf9d6ed7-24b3-40f1-97b9-4cd164301e0e.png">

**Comment by amje** [comment]
@nikita-jpg Seems like not relevant after v5 update. It works in codesandbox with latest version. Feel free to reopen if it still a problem
