### ISSUE TITLE
SELECT display multiple selection issue

### ISSUE THREAD

**Issue by victor-nartov** [gravity-ui/uikit#672]
Hi! 
Please help me to figure out if this is a bug or not... I have single option select which is working great unless I choose option with value that partially includes other option value. For example if i choose value "OAO" my selection also includes "AO"

sorry if silly question... did not manage to find this behaviour in documentation

https://github.com/gravity-ui/uikit/assets/134281658/6ae8abd6-35c0-4f92-85fb-972250df608e

**Comment by korvin89** [comment]
Hey! Could you show all the code of your example?

**Comment by korvin89** [comment]
I can`t reproduce this bug

https://github.com/gravity-ui/uikit/assets/26501073/4c42cfe5-7df4-41d2-af71-d46def94e0bd

**Comment by victor-nartov** [comment]
Hi! I figure out why cause of this behaviour - i ve made a mistake in onUpdate event handler
<img width="833" alt="Screenshot 2023-05-23 at 12 54 08" src="https://github.com/gravity-ui/uikit/assets/134281658/d6af5c10-c1cf-4990-a641-271ceb9de2c1">
