### ISSUE TITLE
Update color value for --yc-color-base-neutral in Dark-Contrast Theme

### ISSUE THREAD

**Issue by ykamendrovskiy** [gravity-ui/uikit#708]
https://github.com/gravity-ui/uikit/blob/a55a041ad092eea072300a177a595fb1078c940d/styles/colors/base/dark-hc.scss#L33

the value should be var(--yc-color-private-white-150)

current value is var(--yc-color-private-white-100) which is the same as the one in Dark Normal. As the value doesn't change between the normal and contrast themes, the contrast doesn't get improved

**Comment by KalachevDev** [comment]
fixed in v5
