### ISSUE TITLE
Fix incorrect usage of qa attribute

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#729]
Check [MenuItem](https://github.com/gravity-ui/uikit/blob/main/src/components/Menu/MenuItem.tsx#L61) and other usages of `qa`

**Comment by tarunsamanta2k20** [comment]
Should I remove the QA attribute?

**Comment by amje** [comment]
> Should I remove the QA attribute?

@tarunsamanta2k20  You are welcome. Correct attribute is `data-qa`

**Comment by KalachevDev** [comment]
@amje seems issue description isn't clear. Correct me if I'm wrong, we should remove `qa` attribute in favour of `data-qa`.
Basically, all components with that render `<div qa="smth"></div>` should be transformed into `<div data-qa="smth"></div>`
