### ISSUE TITLE
Popover ignores autoclosing when openOnHover is false

### ISSUE THREAD

**Issue by Kelayn** [gravity-ui/uikit#846]
Not sure whether this behaviour is determined or not, but it sure is not predictable behaviour.

Issue: 
I need to show an autoclosable popover on the page, that should be displayed by default, and once it's closed - it never reappears until the page reloads.

Expected:
1) setting following props
```
            openOnHover={false}
            initialOpen={true}
            autoclosable
```
2) popover appears by default
3) popover disappears when cursor moves outside it
4) popover doesn't appear until page is refreshed

Current: 
1) setting following props
```
            openOnHover={false}
            initialOpen={true}
            autoclosable
```
2) popover appears by default
3) popover doesn't disappear automatically (clicks outside of popover do hide it)
4) reappears on clicks on anchor element

```
   <Popover
            openOnHover={false}
            initialOpen
            content={'filters here'}
            autoclosable
            placement={'left'}
          >
            <Button
              loading={tableState === 'pending'}
              size={'l'}
              view={'outlined'}
              selected={filtersVisible}
              onClick={triggerFiltersVisible}
            >
              <Icon data={BarsDescendingAlignCenter} />
            </Button>
   </Popover>
```

Can be reproduced in storybook https://preview.gravity-ui.com
setting the initialOpen:true; openOnHover:false; autoclosable: true

**Comment by amje** [comment]
@Kelayn Sry for long response. Current behaviour works as expected, `inititalOpen` doesn't control the open state forever, only the initial render, and toggle clicks switch the open state by default.  If you need full control, consider using Popup component with `open` prop managed from your state.

About 3rd point. `openOnHover` also disables hiding on hover, not sure if it's good or not, but it's expected
