### ISSUE TITLE
Hooks docs and typings

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#881]
Each exported hook must have a README file and follow this template:
```ts
// hooks/useMyHookName.ts

export interface MyHookNameProps {}

export interface MyHookNameResult {}

export function useMyHookName(props: MyHookNameProps): MyHookNameResult {}
```

```ts
// index.ts

// ...
export * from './hooks/useMyHookName';
// ...
```

**Comment by NikitaCG** [comment]
Сall me when we start

**Comment by NikitaCG** [comment]
I suggest attaching PR in the comments, since there will be more than one of them before the issue closes
[useOutsideClick](https://github.com/gravity-ui/uikit/pull/1035)

**Comment by NikitaCG** [comment]
[PR](https://github.com/gravity-ui/uikit/pull/1038) with next hooks: 

- useBodyScrollLock
- useVirtualElementRef
- usePortalContainer

**Comment by NikitaCG** [comment]
PRs:
 - https://github.com/gravity-ui/uikit/pull/1038
 - https://github.com/gravity-ui/uikit/pull/1042
 - https://github.com/gravity-ui/uikit/pull/1049
 - https://github.com/gravity-ui/uikit/pull/1060
 - https://github.com/gravity-ui/uikit/pull/1084
