### ISSUE TITLE
Broken code examples in date-components storybook

### ISSUE THREAD

**Issue by ldrv565** [gravity-ui/uikit#903]
https://preview.gravity-ui.com/date-components/?path=/docs/components-calendar--docs

<img width="882" alt="Screenshot 2023-08-16 at 16 04 03" src="https://github.com/gravity-ui/uikit/assets/40745264/051c1b63-3847-4b03-bbe6-29a5da385991">

**Comment by chervyakovru** [comment]
Hi!
Most likely, you will want to recreate the problem in another repo: https://github.com/gravity-ui/date-components/issues

**Comment by amje** [comment]
Moved issue: https://github.com/gravity-ui/date-components/issues/14
