### ISSUE TITLE
List component does not re-render elements with `virtualized=true` when render function changes and parent component re-renders

### ISSUE THREAD

**Issue by KalachevDev** [gravity-ui/uikit#982]
I'm trying to make repro repo, but facing the following issue - List component refuses to render options despite of specified `--yc-list-height` variable or `display: flex` on parent container - what am I doing wrong? [README link](https://github.com/gravity-ui/uikit/tree/main/src/components/List#virtualization)

https://codesandbox.io/s/magical-lehmann-43tn5z?file=/src/App.js

It works fine with `virtualized: false`

**Comment by mariamelior** [comment]
I have the same problem. When I use virtualized=true in a List and want to show ticks on selected items, the tick shows only after moving mouse and not after a click

It was broken after these changes https://github.com/gravity-ui/uikit/compare/v5.20.0...v5.21.0#diff-72874b9cecaf9f2c29fe3d4767351a1b799410f62b522a138b5e4f2fa6880171L89

The example is showen in https://codesandbox.io/p/sandbox/busy-davinci-pd78ql
